language: python
cache: pip

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

env:
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0

matrix:
    fast_finish: true

    include:
      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }

    exclude:
      - { python: "2.7", env: DJANGO=2.0 }

install:
    - pip install tox tox-travis

script:
    - tox
