branches:
  only:
    - master
language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
install:
    - pip install django==$DJANGO
    - pip install south==0.7.4
script: python runtests.py
