language: python

python:
  - "3.5"

sudo: false

env:
    - TOX_ENV=py35-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=py27-django110
    - TOX_ENV=py36-django111
    - TOX_ENV=py35-django111
    - TOX_ENV=py34-django111
    - TOX_ENV=py27-django111
    - TOX_ENV=py36-django20
    - TOX_ENV=py35-django20
    - TOX_ENV=py34-django20

matrix:
  fast_finish: true

install:
  # Virtualenv < 14 is required to keep the Python 3.2 builds running.
  - pip install tox "virtualenv<14"

script:
    - tox -e $TOX_ENV
